remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

title: Nick M. Blog
author: Nick M.

minima:
  skin: dark
  social_links:
    - title: My LinkedIn Profile   # Tooltip text
      icon: linkedin             # Font Awesome icon ID for LinkedIn
      url: "https://www.linkedin.com/in/nmatamoros/"
